<?php
// /local/yourplugin/config/student_pages.php
defined('MOODLE_INTERNAL') || die();

return [
    'student_dashboard' => [
        'id' => 'student_dashboard',
        'url' => '/theme/rainmake/dashboard.php',
        'layout' => 'rainmake',
        'title' => 'Home',
        'description' => 'Student learning dashboard',
        'icon' => null,
        'category' => 'student',
        'permissions' => ['moodle/comment:view'],
        'parent' => null,
        'order' => 10,
        'navigation' => ['main_nav'],
        'default' => true
    ],
    'student_career_paths' => [
        'id' => 'student_career_paths',
        'url' => '/theme/rainmake/courses.php',
        'layout' => 'rainmake',
        'title' => 'Career Paths',
        'description' => 'All Career Paths',
        'icon' => null,
        'category' => 'student',
        'permissions' => ['moodle/comment:view'],
        'parent' => null,
        'order' => 20,
        'navigation' => ['main_nav'],
    ],
    'student_my_career_paths' => [
        'id' => 'student_my_career_paths',
        'url' => '/theme/rainmake/mycareerpath.php',
        'layout' => 'rainmake',
        'title' => 'My Career Paths',
        'description' => 'My Career Paths',
        'icon' => null,
        'category' => 'student',
        'permissions' => ['moodle/comment:view'],
        'parent' => null,
        'order' => 21,
    ],
    'single_practice' => [
        'id' => 'single_practice',
        'url' => '/theme/rainmake/practice.php',
        'layout' => 'rainmake',
        'title' => 'Practice',
        'description' => 'Practice',
        'order' => 22,
    ],
    'student_about' => [
        'id' => 'student_about',
        'title' => 'About',
        'order' => 30,
        'navigation' => ['main_nav'],
    ],
    'student_contact' => [
        'id' => 'student_contact',
        'title' => 'Contact',
        'order' => 40,
        'navigation' => ['main_nav'],
    ],
    'student_become_superstar_trainer' => [
        'id' => 'student_become_superstar_trainer',
        'title' => 'Become a Superstar Trainer',
        'order' => 50,
        'navigation' => ['main_nav'],
    ],
    'student_profile' => [
        'id' => 'student_profile',
        'url' => '/theme/rainmake/profile.php',
        'layout' => 'rainmake',
        'title' => 'Profile',
        'description' => 'Profile',
        'order' => 60,
    ],
    'admin_dashboard' => [
        'id' => 'admin_dashboard',
        'url' => '/theme/rainmake/admin/dashboard.php',
        'layout' => 'rainmakeadmin',
        'title' => 'Dashboard',
        'description' => 'Admin dashboard',
        'icon' => '/theme/rainmake/pix/icons/admin/ChartBar.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:create'],
        'parent' => null,
        'order' => 60,
        'navigation' => ['admin_nav'],
        'default' => true
    ],
    'admin_career_path_create' => [
        'id' => 'admin_career_path_create',
        'url' => '/theme/rainmake/admin/createcareerpath/basic.php',
        'layout' => 'rainmakeadmin',
        'title' => 'Create Career Path',
        'description' => 'Create Career Path',
        'icon' => '/theme/rainmake/pix/icons/admin/PlusCircle.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:create'],
        'parent' => null,
        'order' => 65,
        'navigation' => ['admin_nav'],
    ],
    'admin_course_create' => [
        'id' => 'admin_course_create',
        'url' => '/theme/rainmake/admin/createcourse/basic.php',
        'layout' => 'rainmakeadmin',
        'title' => 'Create Course',
        'description' => 'Create Course',
        'icon' => '/theme/rainmake/pix/icons/admin/PlusCircle.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:create'],
        'parent' => null,
        'order' => 70,
        'navigation' => ['admin_nav'],
    ],
    'admin_career_paths' => [
        'id' => 'admin_career_paths',
        'url' => '/theme/rainmake/admincourses.php',
        'layout' => 'rainmakeadmin',
        'title' => 'Career Paths',
        'description' => 'All Career Paths',
        'icon' => '/theme/rainmake/pix/icons/admin/Stack.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:create'],
        'parent' => null,
        'order' => 80,
        'navigation' => ['admin_nav'],
    ],
    'admin_students' => [
        'id' => 'admin_students',
        'url' => '/theme/rainmake/admin/students.php',
        'layout' => 'rainmakeadmin',
        'description' => 'Students',
        'title' => 'Students',
        'icon' => '/theme/rainmake/pix/icons/admin/GraduationCap.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:view'],
        'parent' => null,
        'order' => 90,
        'navigation' => ['admin_nav'],
    ],
    'admin_assignments' => [
        'id' => 'admin_assignments',
        'url' => '/theme/rainmake/admin/assignments/tasks.php',
        'layout' => 'rainmakeadmin',
        'description' => 'Admin Assignments',
        'title' => 'Assignments',
        'icon' => '/theme/rainmake/pix/icons/admin/Bookmark.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:view'],
        'parent' => null,
        'order' => 100,
        'navigation' => ['admin_nav'],
    ],
    'admin_comments' => [
        'id' => 'admin_comments',
        'title' => 'Comments',
        'icon' => '/theme/rainmake/pix/icons/admin/ChatCircleDots.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:view'],
        'parent' => null,
        'order' => 110,
        'navigation' => ['admin_nav'],
    ],
    'admin_gradebook' => [
        'id' => 'admin_gradebook',
        'url' => '/theme/rainmake/admin/gradebook.php',
        'layout' => 'rainmakeadmin',
        'description' => 'Gradebook',
        'title' => 'Gradebook',
        'icon' => '/theme/rainmake/pix/icons/admin/Notebook.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:view'],
        'parent' => null,
        'order' => 120,
        'navigation' => ['admin_nav'],
    ],
    'admin_settings' => [
        'id' => 'admin_settings',
        'url' => '/theme/rainmake/adminprofile.php',
        'layout' => 'rainmakeadmin',
        'description' => 'Admin Settings',
        'title' => 'Settings',
        'icon' => '/theme/rainmake/pix/icons/admin/Gear.svg',
        'category' => 'admin',
        'permissions' => ['moodle/course:view'],
        'parent' => null,
        'order' => 130,
        'navigation' => ['admin_nav'],
    ],
    'course_watch' => [
        'id' => 'course_watch',
        'url' => '/theme/rainmake/course.php',
        'layout' => 'rainmake',
        'description' => 'Course watch',
        'title' => null,
        'icon' => null,
        'category' => 'student',
        'permissions' => ['moodle/comment:view'],
        'parent' => null,
        'order' => 140,
        'navigation' => null,
    ],
    'student_career_path' => [
        'id' => 'student_career_path',
        'url' => '/theme/rainmake/careerpath.php',
        'layout' => 'rainmake',
        'description' => 'Career Path',
        'title' => null,
        'icon' => null,
        'category' => 'student',
        'permissions' => ['moodle/comment:view'],
        'parent' => null,
        'order' => 150,
        'navigation' => null
    ],
];
