<?php
$functions = [
    'local_rainmake_backend_create_empty_course' => [
        'classname'   => 'local_rainmake_backend\external\create_empty_course_endpoint',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'Creates empty course and attach it to careerpath',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'local_rainmake_backend_get_course_data' => [
        'classname'   => 'local_rainmake_backend\external\get_course_data',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'Returns basic course info',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'local_rainmake_backend_get_new_courses' => [
        'classname'   => 'local_rainmake_backend\external\get_new_courses',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'Returns courses that are not in the current career path',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'local_rainmake_backend_get_course_new_user_trainers' => [
        'classname'   => 'local_rainmake_backend\external\get_course_new_user_trainers',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'Returns courses that are not in the current career path',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'local_rainmake_backend_get_careerpath_enrolment_users' => [
        'classname'   => 'local_rainmake_backend\external\get_careerpath_enrolment_users',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'Returns enrolled and available users for a career path',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'local_rainmake_backend_course_user_unenroll' => [
        'classname'   => 'local_rainmake_backend\external\course_user_unenroll',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'unenroll a user from course',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'local_rainmake_backend_search_users' => [
        'classname'   => 'local_rainmake_backend\external\search_users',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'Search users by name, username, or email',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'local_rainmake_backend_search_courses' => [
        'classname'   => 'local_rainmake_backend\external\search_courses',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'Search courses by fullname or shortname',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'local_rainmake_backend_search_curriculum' => [
        'classname'   => 'local_rainmake_backend\external\search_curriculum',
        'methodname'  => 'execute',
        'classpath'   => 'local/rainmake_backend/classes/external',
        'description' => 'Search curriculum items (courses, modules, lectures)',
        'type'        => 'read',
        'ajax'        => true,
    ],
];
